### ISSUE TITLE
YouTube - User's Most Recent Videos

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#171]

**Comment by slickchris** [comment]
ch808 test for "YouTube - User's Most Recent Videos" using the provided example of nationalgeographic (because since YT switched to URL 'handles' it's now difficult to find 'username' URLs).

ch808 frontend page link: [https://ch808shoots.com/y-4-0-yt-users-most-recent-videos/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1286&action=edit&classic-editor=1](url)

ch808 FT Social settings backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1539&action=edit#youtube_feed](url)

**Comment by slickchris** [comment]
Making the YT feed with the large video... there appears to be an issue. The large video does not load, but if you click on any of the smaller videos, they will play in the large video place. Not sure if this is by design or a bug. But definitely different from v3.0.

**Comment by justinslickremix** [comment]
@spencerslickremix Yea strange the first large Thumb is not getting image and shows an error when clicked.

![Image](https://user-images.githubusercontent.com/50183104/219117486-62bfa37f-8ff7-4e62-afd6-2c1a2bb7e324.png)

**Comment by SlickRemix** [comment]
@SlickRemix @justinslickremix this is now fixed
