### ISSUE TITLE
Combined - Instagram, Facebook, Twitter, YouTube. Example of each Feed Type Too.

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#174]

**Comment by slickchris** [comment]
ch808 test for "Combined Streams - ALL 4" (*I had tested this a few days ago and all worked fine. I went back in just now, and 3 of the 4 tokens saved, but not YouTube. So, in trying to reacquire a YT token, it did the loop again, 3 times before it stuck (using API Key). Then, had to clear FTS cache for it to take, as the "live editing cache" didn't do it, needed a manual FTS cache clear). ANYWAY, I got it working (for now), here are the links:

ch808 frontend page link: [https://ch808shoots.com/zz-4-0-cs-all-feeds/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1292&action=edit](url)

ch808 FT Social settings backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1424&action=edit#combine_streams_feed](url)

**Comment by slickchris** [comment]
CS test for each feed: just FB test

ch808 frontend page link: [https://ch808shoots.com/zz-cs-fb-only-4-0-test/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1572&action=edit&classic-editor=1](url)

ch808 FT Social settings backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1570&action=edit#combine_streams_feed](url)

**Comment by slickchris** [comment]
CS test for IG feed only.

ch808 frontend page link: [https://ch808shoots.com/zz-cs-ig-only-4-0-test/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1575&action=edit&classic-editor=1](url)

ch808 FT Social settings backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1593&action=edit#combine_streams_feed](url)

**Comment by slickchris** [comment]
CS test for IG hashtags (#moodygrams)

ch808 frontend page link: [https://ch808shoots.com/zz-cs-ig-hashtag-only-4-0-test/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1584&action=edit&classic-editor=1](url)

ch808 FT Social settings backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1600&action=edit#combine_streams_feed](url) 

For this test, the live updates on the FT Social backend page seemed to struggle, but the frontend page loaded perfectly (screenshots)



![Image](https://user-images.githubusercontent.com/57366009/216097788-df96675c-ea68-4235-bd59-961960733329.png)
![Image](https://user-images.githubusercontent.com/57366009/216097789-c69ccc80-0693-4677-b238-05cd6bfa8f37.png)

**Comment by slickchris** [comment]
CS test for Twitter feed only.

ch808 frontend page link: [https://ch808shoots.com/zz-cs-twitter-only-4-0-test/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1578&action=edit&classic-editor=1](url)

ch808 FT Social settings backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1608&action=edit#combine_streams_feed](url)


*Okay... so.... Who TF knows what's going on with Twitter these days??? Anyway, on this Twitter CS solo test, I used the exact same settings as the above Instagram Hashtag test. But, (using the GoPro Twitter account) only 2 posts are showing (as I set 18 and 18) and checked the GoPro Twitter page and saw that there are 18 recent posts (unless Twitter changed their API to past 24 hours instead of past 7 days??? 

*Also, of the 2 posts. one pic & one video. They both display when set to "below" and only one displays when set to "above" (screenshots) so...idk?



![Image](https://user-images.githubusercontent.com/57366009/216103300-7852976c-ddd9-4eb4-8fee-90420e8c1a54.png)
![Image](https://user-images.githubusercontent.com/57366009/216103301-e6fa3baa-bea2-4f39-a9d2-b608f132221b.png)

**Comment by slickchris** [comment]
CS test for YouTube feed only.

ch808 frontend page link: [https://ch808shoots.com/zz-cs-youtube-only-4-0-test/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1581&action=edit&classic-editor=1](url)

ch808 FT Social settings backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1619&action=edit#combine_streams_feed](url)

**The YT CS feed works fine. However, getting the token keeps putting me through the loops. Eventually it sticks, sometimes 2 tries, sometimes 3 tries.
