### ISSUE TITLE
Settings Page -  Make sure all the color options etc work with feeds.

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#190]

**Comment by slickchris** [comment]
ch808 test for color options with FB feed. All seem to work.

ch808 frontend page link: [https://ch808shoots.com/zzz-4-0-color-test-1-fb/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1630&action=edit&classic-editor=1](url)

ch808 FT Social settings backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1646&action=edit#facebook_feed](url)

**Comment by slickchris** [comment]
ch808 test for IG Basic feed. No color options other than for the Load More button. Color options are working fine.

ch808 frontend page link: [https://ch808shoots.com/zzz-4-0-color-test-2-ig-basic/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1633&action=edit&classic-editor=1](url)

ch808 FT Social settings backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1654&action=edit#instagram_feed](url)

**Comment by slickchris** [comment]
ch808 test for IG Biz feed. *No color options here either. Like IG Basic, only load more button color options available. Can't find them anywhere. ***Is this something that's missing???*** IG Feed Color options? 

The color options are present in the FB Style options, but not IG.

Anyway, I tested. And since only Load More button color options exist, I tested and it is working fine.

ch808 frontend page link: [https://ch808shoots.com/zzz-4-0-color-test-3-ig-biz/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1636&action=edit&classic-editor=1](url)

ch808 FT Social settings backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1665&action=edit#instagram_feed](url)

Again, aside from Load More button, no IG feed color options (screenshot):



![Image](https://user-images.githubusercontent.com/57366009/216349878-97f86e95-81aa-4c2b-860d-dd1ec1bd318f.png)

**Comment by slickchris** [comment]
ch808 test for Twitter color & style options. All options appear to be working fine.

ch808 frontend page link: [https://ch808shoots.com/zzz-4-0-color-test-4-twitter/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1639&action=edit&classic-editor=1](url)

ch808 FT Social settings backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1674&action=edit#twitter_feed](url)
