### ISSUE TITLE
CSS problems

### ISSUE THREAD

**Issue by taker218** [SlickRemix/feed-them-social#63]
I already posted it on the wordpress support forum and was asked to post my findings here.

The whole thread is visible here:
https://wordpress.org/support/topic/cant-create-short-codes/#post-11220205

In the settings-page.css the shortcode-form-selector has a fixed height of 40px, this must be set to auto, so it will be displayed the right way.

When I select a feed to create the shortcode for it doesn't display the corresponding div.
I just did the following in the firefox developer tools to make them visible:
`<form class="feed-them-social-admin-form shortcode-generator-form fts-fb-page-shortcode-form facebook_options_wrap" style="display: block;">`

`style="display:block;"` is the one thing I added to make it visible.
I don't know where this problem is coming from, so if anyone knows where to fix it, please let me know.

If there are any questions, please don't be afraid to ask. I'm also happy to debug it on my page, since it's not really active.

Best regards,
Thomas

**Comment by SlickRemix** [comment]
Patching this now and will be pushing it here shortly for version 2.6.6. Thanks again for looking into this. Spencer

**Comment by SlickRemix** [comment]
Can you see if removing height auto and put it back to height:40px and then add line-height:40px and see if that makes the select option is fully visible for me please? Spencer

**Comment by SlickRemix** [comment]
As for the display:block being added to the fts-fb-page-shortcode-form facebook_options_wrap class, can you double check out don't have any javascript errors in your console, if so that might be preventing that div from opening proper.

**Comment by taker218** [comment]
I just did the above mentioned with the line-height, but it didn't work.
It's the same as before.

And I found the problem with the display:block.

Another plugin threw an js error and therefore the display:block wasn't able to be set.
This is working just fine now

**Comment by SlickRemix** [comment]
What if you leave the height 40px on the select and then add this ( its the id for the form wrapping the select.
`#feed-selector-form {height:40px;}`
I really want to make that select look bigger than the rest so it stands out as being different and setting it to auto makes it real skinny. If that does not work can you try a few things to see if you can work around the select height that is set to make the select visible?

**Comment by taker218** [comment]
When I take out the following in the shortcode-form-selector it displays correctly.
`padding:15px;`

If I do this it doesn't actually matter if the feed-selector-form height is set or not
<img width="375" alt="feed_them_social_settings" src="https://user-images.githubusercontent.com/15029277/53654264-9a46f280-3c4d-11e9-8935-97f083692dff.png">

**Comment by taker218** [comment]
And I put the height of the shortcode-form-selector back to 40px

**Comment by SlickRemix** [comment]
Awesome, funny you mention the padding:15px cause I saw that too and removed it because it was doing nothing for me on my mac browsers. Not sure why that was ever there honestly.

Alright prepping for 2.6.6 push. I fixed a few other things in this update, I add you to the list too.

= Version 2.6.6 Friday, March 1st, 2018 =
   * NEW: Facebook Feed: Make Extra Image Attachment Elements Accessible. Thanks to [KZeni](https://github.com/KZeni) for contributing.
   * FIX: Facebook Feed: If we are unable to get the commenter's profile photo for privacy reasons we then load the default comment image now included in the plugin. This will greatly reduce errors in our APP and speed up load time.
   * FIX: Twitter Feed: Retweet videos not coming up.
   * FIX: Settings Page: The select social network option was unusable on some Windows machines. Thanks to [Taker218](https://github.com/SlickRemix/feed-them-social/issues/63) for helping us fix this problem.
   * MISC FIX: Translatable strings, misspellings etc and CSS for Settings page feed select option.
